language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq gromacs-dev
  - sudo apt-get install -qq liblapack-dev
  - sudo apt-get install -qq libblas-dev
  - sudo apt-get install -qq mpich2

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON -DBUILD_PARALLEL=ON
  - make
  - make install
  - cd test
  - cp $HOME/ProtoMol/bin/ProtoMol .
  - python test.py
