language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      libblas-dev
      liblapack-dev
      gromacs-dev
      openmpi

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON -DBUILD_PARALLEL=ON
  - make
  - make install
  - cd test
  - cp $HOME/ProtoMol/bin/ProtoMol .
  - python test.py --serial --parallel --errorfailure
