language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq gromacs
  - sudo apt-get install -qq liblapack-dev
  - sudo apt-get install -qq libblas-dev

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/ProtoMol -DBUILD_LAPACK_TYPE=lapack -DBUILD_GROMACS=ON.
  - make
  - make install

notifications:
  email: false
